### PR TITLE
Descriptive updates

### PR DESCRIPTION
**Pull request by rosibaj**
- display name
- descriptive notes based on Beta Feedback from users
- more informative descriptions

### CODE REVIEW

**Comment by wajiha-oicr** [comment]
Looks like the JSON failed to parse for sample registration. I think there's a missing comma on line 55

**Comment by hknahal** [comment]
@rosibaj Looks good. There's just a small typo on line 281, where it says "Tumor" instead of "Tumour":

(displayName": "Post-therapy **Tumor** Staging System")

**Comment by rosibaj** [comment]
@wajiha-oicr its fine to add to meta - no changes needed.  Display name will be used by downstream apps like clinical

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr its fine to add to meta - no changes needed. Display name will be used by downstream apps like clinical

sounds good, thank you for clarifying

**Comment by rosibaj** [comment]
@hknahal found two instances of (tumor) and fixed both.  one was in a codelist.

**Pull request merged**
