### PR TITLE
378 rt criteria

### PR DESCRIPTION
**Pull request by hknahal**
Addition of new response_to_treatment_criteria_method field and validation check
Related to https://github.com/icgc-argo/argo-dictionary/issues/378

### CODE REVIEW

**Comment by hknahal** [comment]
** New response criteria **
|RECIST | iRECIST | Cheson Oncology Response Criteria | Response Assessment in Neuro-Oncology (RANO) | ELN Dohner AML Oncology Response Criteria | Physician Assessed Response Criteria |
|  -- | -- | -- | -- | -- | --
| Complete response | Immune complete response (iCR) | Complete remission | Complete response | Complete remission without measurable residual disease (CR MRD−) | Physician assessed complete response |
| Partial response | Immune partial response (iPR) | Partial remission | Partial response | Complete remission | Physician assessed partial response |
| Progressive disease | Immune unconfirmed progressive disease (iUPD) | Stable disease | Minor response | Complete remission with incomplete hematologic recovery (CRi) | Physician assessed stable disease |
| Stable disease | Immune confirmed progressive disease (iCPD) | Progressive disease | Stable disease | Morphologic leukemia-free state |  
| No evidence of disease (NED) | Immune stable disease (iSD) |   | Progressive disease | Partial remission |  
  |   |   |   | Primary refractory disease |  
  |   |   |   | Hematologic relapse (after CRMRD-, CR, CRi) |  
  |   |   |   | Molecular relapse (after CRMRD-) |  
  |   |   |   | Stable disease |  
  |   |   |   | Progressive disease |  


NOTE: The term "Progressive disease" is used rather than "Disease progression".

Test files:


Test case 1: "response_to_treatment_criteria_method" = `RECIST` but the `response_to_treatment` = `Minor response` which does not belong to the RECIST criteria (it belongs in a different response criteria (ELN Dohner AML Oncology Response Criteria). 

Expected Validation: Validation should fail and report error message:
378_test_case1

**Comment by hknahal** [comment]
**Test case 1:** A "response_to_treatment" term that does not belong to the criteria submitted in the "response_to_treatment_criteria_method" should trigger a failed validation and error message. In this example, the "response_to_treatment_criteria_method" = `RECIST` but the `response_to_treatment` = `Minor response` which does not belong to the RECIST criteria (it belongs in a different response criteria (ELN Dohner AML Oncology Response Criteria). 

**Test files:**
[donor.txt](https://github.com/icgc-argo/argo-dictionary/files/10249615/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-dictionary/files/10249616/primary_diagnosis.txt)
[treatment.txt](https://github.com/icgc-argo/argo-dictionary/files/10249618/treatment.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-dictionary/files/10249614/chemotherapy.txt)
[radiation_v1.15.txt](https://github.com/icgc-argo/argo-dictionary/files/10249617/radiation_v1.15.txt)

**Expected Validation:** Validation should fail and report error message:
378_test_case1

**Test case 2:** If a "response_to_treatment" term belongs to the criteria submitted in the "response_to_treatment_criteria_method", the validation should pass. For example, if `response_to_treatment_criteria_method` = `Cheson Oncology Response Criteria` and "response_to_treatment" = `Stable disease`, the validation should pass because the term "Stable disease" exists in the Cheson Oncology Response Criteria.

**Test Files:**
[donor.txt](https://github.com/icgc-argo/argo-dictionary/files/10249615/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-dictionary/files/10249616/primary_diagnosis.txt)
[treatment.txt](https://github.com/icgc-argo/argo-dictionary/files/10249649/treatment.txt)
[chemotherapy.txt](https://github.com/icgc-argo/argo-dictionary/files/10249614/chemotherapy.txt)
[radiation.txt](https://github.com/icgc-argo/argo-dictionary/files/10249650/radiation.txt)

**Expected Validation:**:
test_case2

**Comment by hknahal** [comment]
Test case 3 updated to permit `response_to_treatment_criteria_method` and `response_to_treatment` fields to be empty if `treatment_type` = `No treatment`. The previous test case which allowed these fields to be `Not applicable` made the dictionary inconsistent with other core conditional fields, which are allowed to be empty if they do not apply.

**Test files:**
[donor_testcase3.txt](https://github.com/icgc-argo/argo-dictionary/files/10272089/donor_testcase3.txt)
[primary_diagnosis_testcase3.txt](https://github.com/icgc-argo/argo-dictionary/files/10272090/primary_diagnosis_testcase3.txt)
[treatment_testcase3.txt](https://github.com/icgc-argo/argo-dictionary/files/10272092/treatment_testcase3.txt)
[radiation_testcase3.txt](https://github.com/icgc-argo/argo-dictionary/files/10272091/radiation_testcase3.txt)
[chemotherapy_testcase3.txt](https://github.com/icgc-argo/argo-dictionary/files/10272088/chemotherapy_testcase3.txt)

**Test case 3:**

| Row in treatment file | treatment_type | response_to_treatment_criteria_method | response_to_treatment | Expected validation |
|--|--|--|--|--|
| 2 | Chemotherapy | (empty) | (empty) | Fail |
| 3 | Radiation therapy | Cheson Oncology response criteria | complete remission | Pass |
| 4 | No treatment | (empty) | (empty) | Pass |
| 5 | No treatment | RECIST | partial response | Fail | 
| 6 | Chemotherapy | (empty) | complete response | Fail |
| 7 | Radiation therapy | iRECIST | (empty) | Fail |

**Comment by hknahal** [comment]
Fixed the validation script to make `response_to_treatment_criteria_method` and `response_to_treatment` fields to be empty if `treatment_type` = `No treatment`. To test, please use Test cases 1 & 2 from [this comment](https://github.com/icgc-argo/argo-dictionary/pull/387#issuecomment-1355707842) and Test case 3 from [here](https://github.com/icgc-argo/argo-dictionary/pull/387#issuecomment-1360116373).

**Comment by Buwujiu** [comment]
Tested in QA TEST-CA, working as expected!

**Review by Buwujiu — APPROVED** [review]

**Pull request merged**
