### PR TITLE
375 radiation boost

### PR DESCRIPTION
**Pull request by hknahal**
Related to https://github.com/icgc-argo/argo-dictionary/issues/375

### CODE REVIEW

**Comment by Buwujiu** [comment]
> reference_radiation_treatment_id

Tested all cases in ALEXIS-INTL in QA, working as expected!

**Review by Buwujiu — APPROVED** [review]

**Comment by hknahal** [comment]
Pending clinical changes (https://github.com/icgc-argo/argo-clinical/issues/856)

**Comment by puneet-oicr** [comment]
May be moved to 1.18 because testing is pending

**Comment by lindaxiang** [comment]
The dictionary change for this feature and dependent clinical change (https://github.com/icgc-argo/argo-clinical/issues/856) have both been tested in QA. This PR can be merged.

**Pull request merged**
