### PR TITLE
Add extended schemas

### PR DESCRIPTION
**Pull request by rosibaj**
- add "core' field designation
- update the current data to the WIP
- added follow-up as a new schema

### CODE REVIEW

**Comment by rosibaj** [comment]
@hardeep i added some of the recent changes (scripts are still placeholders) so we can work on the data dictionary and start to incorporate new files.  Please scan and let me know any changes!

**Comment by hknahal** [comment]
@rosibaj I'm not sure if this matters, but can the "core" field have two different types? For example, boolean true/false like [here](https://github.com/icgc-argo/argo-dictionary/blob/add_extended_schemas/schemas/donor.json#L53) and text like [here](https://github.com/icgc-argo/argo-dictionary/blob/add_extended_schemas/schemas/donor.json#L65)

Also, does this mean if the "core" is missing, then it's assumed the field is optional?

**Comment by rosibaj** [comment]
@hknahal 2nd instance is a mistake :) will fix. 

Yes, the assumption is if not core then `extended` --> Extended is the language christina/your excel has been using, not `optional`

**Comment by hknahal** [comment]
The field names are mixed up for "anatomic_site_progression_or_recurrence" and "method_of_progression_status" (they just need to be swapped)

**Comment by rosibaj** [comment]
@hknahal  updated

**Comment by hknahal** [comment]
Can we add a "validateWithMagic" to the "[tumour_grade](https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/specimen.json#L379)" field too because it depends on the tumour grading system used?  For example, if they use the Gleason scoring system, we can expect Gleason scores (which range from 1-10).  But for other tumour grading systems, like non-Hodgkins lymphoma, their tumour grading terminology might be "Low grade" and "High grade".

**Comment by rosibaj** [comment]
@hknahal  updated

**Pull request merged**
