### PR TITLE
Dictionary 1.19 merge to master

### PR DESCRIPTION
**Pull request by hknahal**
Tickets to test in QA using Dictionary version `127.1`:

- [x] https://github.com/icgc-argo/argo-dictionary/issues/392
- [x] https://github.com/icgc-argo/argo-dictionary/issues/405
- [x] https://github.com/icgc-argo/argo-dictionary/issues/413
- [x] https://github.com/icgc-argo/argo-dictionary/issues/358

### CODE REVIEW

**Comment by hknahal** [comment]
- Test https://github.com/icgc-argo/argo-dictionary/issues/392
Registered samples using [sample_registration.csv](https://github.com/icgc-argo/argo-dictionary/files/12704089/sample_registration.csv) in `HNAHAL-CA` program using 2 new specimen_type terms.

Was able to successfully register two tumour specimens using the 2 new specimen_type terms:
new_specimen_type_terms

**Comment by hknahal** [comment]
- Test https://github.com/icgc-argo/argo-dictionary/issues/405
   Attempted to register LUCA-KR incorrect IDs in `TEST-CA`: 
[sample_registration_luca-kr_incorrect_ids_submitted_to_test-ca.csv](https://github.com/icgc-argo/argo-dictionary/files/12704151/sample_registration_luca-kr_incorrect_ids_submitted_to_test-ca.csv)

Validation of incorrect IDs fails as expected. Returns an error indicating the submitted IDs do not conform to required regex:

test-ca_sample_reg_error_incorrect_ids

**Comment by hknahal** [comment]
- Test https://github.com/icgc-argo/argo-dictionary/issues/413
   Submitted new response_to_treatment term `Physician assessed progressive disease` in `HNAHAL-CA`
   Passed validation as expected with new response_to_treatment term:
hnahal-ca_new_rtt

**Comment by hknahal** [comment]
- Test https://github.com/icgc-argo/argo-dictionary/issues/358 by testing all test cases from https://github.com/icgc-argo/argo-clinical/issues/854

All test cases in https://github.com/icgc-argo/argo-clinical/issues/854 were tested in DEV and QA and pass or fail validation as expected.

**Review by lindaxiang — APPROVED** [review]

**Pull request merged**
