### PR TITLE
add new primary ids

### PR DESCRIPTION
**Pull request by rosibaj**
- add primary id for `primary_diagnosis`
- add connection between `primary_diagnosis` and `treatment`, `specimen`, `followup`
- add connection between `treatment` and `followup`

### CODE REVIEW

**Comment by rosibaj** [comment]
@hknahal I went ahead and made this PR as we need to work on this in the next sprint.  Can you please review?

**Comment by blabadi** [comment]
General question about these submitter ids, I assume these require data validation to see if someone submits a follow up the primary diagnosis Id should either exist or being uploaded (i.e. we validate existence of the foreign key)

the other note is that releasing this dictionary version has to be done hand in hand with clinical code due to code changes, otherwise they will go out of sync.  

that also implies if you need to update the dictionary for other changes, don't merge this because it may block releasing the other changes.

**Comment by rosibaj** [comment]
@blabadi 

1) As this is a PR for the dictionary change, I did not include any validation rules in this tickets PR. I set the required/not required on this to get the PR started, but Hardeep needs to confirm on each entity if this should be required.   I have added the point about the validation check to the corresponding clinical ticket.  https://github.com/icgc-argo/argo-clinical/issues/451

2) I specifically have included these two tickets together in the sprint for this reason.   

3) In this sprint, I think that this is going to be an acceptable thing.  We can bundle things into one dictionary release at the next release.  With dictionary changes, we do not want to do a migration for every change, it is easier to make bulk changes sometimes.

**Comment by hknahal** [comment]
One of the questions @blabadi asked earlier - can a single specimen be linked to more than one primary diagnosis? I confirmed with the working group  - a single specimen cannot be used to diagnose more than one cancer. So this means that a `submitter_specimen_id` will only be associated with one `submitter_primary_diagnosis_id` (the way we have it is correct).

**Comment by blabadi** [comment]
If this is ready, I need to test in develop & then QA

**Comment by blabadi** [comment]
it may need a sync with master first

**Comment by rosibaj** [comment]
@blabadi I think i have rebased onto master correctly - i requested reapproval before merge

**Pull request merged**
