### PR TITLE
added T,N,M codelists based on AJCC 7th and 8th editions

### PR DESCRIPTION
**Pull request by hknahal**

### CODE REVIEW

**Comment by hknahal** [comment]
Related to https://github.com/icgc-argo/argo-dictionary/issues/73

**Comment by hknahal** [comment]
Thanks @rosibaj Forgot about the post_therapy fields! I updated it to include the codelist references for those fields now.

**Comment by rosibaj** [comment]
@hknahal should we remove the other editions as well? pre AJCC 7th edition?

**Comment by hknahal** [comment]
@rosibaj Yes, I'm doing that in https://github.com/icgc-argo/argo-dictionary/issues/122

**Comment by hknahal** [comment]
Related to https://github.com/icgc-argo/argo-dictionary/issues/73

**Pull request merged**
