### PR TITLE
added script validation to validate line_of_treatment optional field

### PR DESCRIPTION
**Pull request by hknahal**
Related to https://github.com/icgc-argo/argo-dictionary/issues/261

### CODE REVIEW

**Comment by hknahal** [comment]
Added validation script to ensure `line_of_treatment` is consistent with `is_primary_treatment`:
- if `is_primary_treatment` is `yes`, then `line_of_treatment` should not be submitted.
- if `is_primary_treatment` is `no` and a value is submitted for `line_of_treatment`, it should be greater than 1.
- if `is_primary_treatment` is `unknown`, `line_of_treatment` should not be submitted.

**Comment by hknahal** [comment]
Testing updates in QA using version `91.8` of dictionary. Came across this error where `is_primary_treatment` is `Yes` and `line_of_treatment` is `1`. Was expecting error message indicated in script validation (see [here](https://github.com/icgc-argo/argo-dictionary/blob/261_line_of_treatment_script/references/validationFunctions/treatment/lineOfTreatment.js#L39)) (ie. `The 'line_of_treatment' field should not be submitted if this treatment is the primary treatment.`). But it instead says this:

treatment_error

It seems the order of validation goes like this: `range` validation is done **_before_** the script validation, and in this case since the `line_of_treatment` value is out of range (it is `1`), the clinical validation returns an error message for that, but does not return error message from script validation.

One way to get around this is to remove the `range` restriction from `line_of_treatment`:
```
{
      "name": "line_of_treatment",
      "description": "Indicate the line of treatment if it is not the primary treatment.",
      "valueType": "integer",
      "restrictions": {
        "script": "#/script/treatment/checkWhenNoTreatment",
        "range": {
           "exclusiveMin": 0
        }
      },
      "meta": {
        "displayName": "Line Of treatment",
        "examples": "2,3,4"
      }
    },
```
And update the script validation instead to include a check to ensure `line_of_treatment` is greater than 1.

**Comment by hknahal** [comment]
Tested above changes in QA using version `91.9` (removed `range` restriction from `line_of_treatment`). This time the error message is correct:

treatment_error_corrected

**Review by rosibaj — DISMISSED** [review]
this lgtm for now - will test with dictionary as well

**Review by rosibaj — APPROVED** [review]

**Pull request merged**
